trigger:
- master

pool:
  name: vm88  # Name of your self-hosted agent pool

stages:
- stage: Build
  displayName: Maven Build Stage
  jobs:
  - job: MavenBuild
    displayName: 'Run mvn package on vm88'
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'package'
        options: '-X'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
